/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Group8;

import GUIStuff.AnimatedPanel;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.PopupMenu;
import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.*;
import javax.swing.JPanel;

/**
 *
 * @author kcnre
 */
public class Menu extends javax.swing.JFrame {

    private UserInfo user1 = new UserInfo("Guest");
    private UserInfo user2 = new UserInfo("Guest2");
    
    private Color c1 = Color.GRAY, c2 = Color.CYAN;    
    /**
     * Creates new form MenuGUI
     */
    public Menu() {
       //Creates a jpanel that is behind the menu
       this.setContentPane(new AnimatedPanel());
       initComponents();
       //sets the background color
       this.getContentPane().setBackground(Color.decode( "#d4f4dd" )); 
    }
    
    public Menu(Color c1, Color c2) {
       this.c1 = c1;
       this.c2 = c2;
       //Creates a jpanel that is behind the menu
       this.setContentPane(new AnimatedPanel());
       initComponents();
       //sets the background color
       this.getContentPane().setBackground(Color.decode( "#d4f4dd" ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        CompVPlayerGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        PlayerName1 = new javax.swing.JLabel();
        PlayerNameField1 = new javax.swing.JTextField();
        VersusLabel = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        ComputerRadioButton = new javax.swing.JRadioButton();
        PlayerNameField2 = new javax.swing.JTextField();
        PlayerRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);

        titleLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Ultimate TIC TAC TOE");

        PlayerName1.setText("User Name: ");

        PlayerNameField1.setText("Guest");
        PlayerNameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerNameField1ActionPerformed(evt);
            }
        });

        VersusLabel.setText("Versus:");

        btnStart.setText("Start Game");
        btnStart.setToolTipText("");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnSettings.setText("Settings");
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        CompVPlayerGroup.add(ComputerRadioButton);
        ComputerRadioButton.setText("Computer");
        ComputerRadioButton.setOpaque(false);
        ComputerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputerRadioButtonActionPerformed(evt);
            }
        });

        PlayerNameField2.setText("Guest2");
        PlayerNameField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerNameField2ActionPerformed(evt);
            }
        });

        CompVPlayerGroup.add(PlayerRadioButton);
        PlayerRadioButton.setText("Player");
        PlayerRadioButton.setMaximumSize(new java.awt.Dimension(103, 29));
        PlayerRadioButton.setMinimumSize(new java.awt.Dimension(103, 29));
        PlayerRadioButton.setOpaque(false);
        PlayerRadioButton.setSelected(true);
        PlayerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(VersusLabel)
                                .addGap(77, 77, 77)
                                .addComponent(ComputerRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PlayerName1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PlayerNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlayerRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlayerNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSettings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(138, 138, 138))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(titleLabel)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayerNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlayerNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlayerName1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VersusLabel)
                    .addComponent(ComputerRadioButton)
                    .addComponent(PlayerRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSettings)
                .addGap(18, 18, 18)
                .addComponent(btnQuit)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        this.pack();        
        this.setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void PlayerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        PlayerNameField2.setVisible(true);
    }                                                 

    private void ComputerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        PlayerNameField2.setVisible(false);
    }                                                   

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        System.exit(0);
    }                                       

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {                                            
        if (user1.getUsername() == "Guest" && user2.getUsername() == "Guest2") {
            Settings s = new Settings();
            s.setVisible(true);
            dispose();
        } else {
            Settings s = new Settings(user1.getUsername());
            s.setVisible(true);
            dispose();
        }
    }                                           

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Game s = new Game(c1,c2, user1.getUsername());
        s.setVisible(true);
        dispose();
    }                                        

    private void PlayerNameField1ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        user1.setUsername(this.PlayerNameField1.getText()); 
        
        // Once the user has entered his username, it will create or read his profile
        Charset charset = Charset.forName("US-ASCII");
        String filePathString = "userProfiles/" + user1.getUsername() + "profile";
        Path file = Paths.get(filePathString);
        File f = new File(filePathString);
        
        if (f.exists()) {

        } else {
            String firstLine = "Games Played: 0\n";
            String secondLine = "Games Won: 0\n";
            
            try (BufferedWriter writer = Files.newBufferedWriter(file, charset)) {
                writer.write(firstLine, 0, firstLine.length());
                writer.write(secondLine, 0, secondLine.length());
            } catch (IOException x) {
                System.err.format("IOException: %s%n", x);
            }
        }
    }                                                

    private void PlayerNameField2ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        user2.setUsername(this.PlayerNameField1.getText()); 
    }                                                

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup CompVPlayerGroup;
    private javax.swing.JRadioButton ComputerRadioButton;
    private javax.swing.JLabel PlayerName1;
    private javax.swing.JTextField PlayerNameField1;
    private javax.swing.JTextField PlayerNameField2;
    private javax.swing.JRadioButton PlayerRadioButton;
    private javax.swing.JLabel VersusLabel;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnStart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration                   

}
